notifications:
  email: false
language: c #NOTE: this will set CC=gcc which might cause trouble
before_script:
 - if [ ${BUILD_ARCH:-0} = arm-aapcs ] ; then
    sudo apt-get -qq install srecord &&
    $WGET https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update/+download/gcc-arm-none-eabi-5_4-2016q2-20160622-linux.tar.bz2 &&
    tar xjf gcc-arm-none-eabi-5_4-2016q2-20160622-linux.tar.bz2 -C /tmp/ &&
    sudo cp -f -r gcc-arm-none-eabi-5_4-2016q2-20160622/* /usr/local/ &&
    rm -rf /tmp/gcc-arm-none-eabi-* gcc-arm-none-eabi-*-linux.tar.bz2 &&
    arm-none-eabi-gcc --version ;
  fi

script:
  ## regression-tests/Makefile handles most of generic logic
  - "make"
env:
  ## This magically kick-off parallel jobs for each of the for the sets
  ## of environment variable defined below
  - BUILD_ARCH='arm-aapcs'
